stages:
  - install
  - test
  - sast
  - build
  - deploy_local
  - terraform_plan

default:
  tags:
    - local  # Vérifie bien que ce tag correspond à ton Runner sur GitLab

variables:
  APP_NAME: "secnotes"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

# Cache pour accélérer les futurs builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .sonar/cache/

install_dependencies:
  stage: install
  image: node:20-alpine
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

run_tests:
  stage: test
  image: node:20-alpine
  script:
    - npm test

sonarqube_scan:
  stage: sast
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.token=$SONAR_TOKEN
      -Dsonar.projectKey=secnotes
      -Dsonar.sources=src
  allow_failure: true

docker_build:
  stage: build
  script:
    - docker build -t secnotes:$IMAGE_TAG .
    - docker tag secnotes:$IMAGE_TAG secnotes:latest

deploy_k8s_local:
  stage: deploy_local
  only:
    - main
  script:
    - kubectl apply -f k8s/