deploy_k8s_local:
  stage: deploy_local
  image: 
    name: bitnami/kubectl:latest  # <--- Deux espaces devant 'name'
    entrypoint: [""]              # <--- Deux espaces devant 'entrypoint'
  only:
    - main
  tags:
    - local
  script:
    - echo "[deploy] Connexion au cluster Kubernetes local..."
    - echo "[deploy] Simulation du déploiement des manifestes (Mode Lab)..."
    - echo "deployment.apps/secnotes-deployment created (dry-run)"
    - echo "service/secnotes-service created (dry-run)"
    - echo "configmap/secnotes-config created (dry-run)"
    - echo "[deploy] Déploiement simulé avec succès !"